project_id = "oeyklikylaitlgwltvup"

[functions.generate-diagnosis]
verify_jwt = false

[functions.validate-pyg-data]
verify_jwt = true

[functions.import-pyg-anual]
verify_jwt = true

[functions.import-company-profile]
verify_jwt = true

[functions.import-balance]
verify_jwt = true

[functions.import-pyg-analytic]
verify_jwt = true

[functions.import-ratios]
verify_jwt = true

[functions.import-cashflow]
verify_jwt = true

[functions.import-debts]
verify_jwt = true

[functions.import-debt-service]
verify_jwt = true